config/routes.rb
Rails.application.routes.draw do

  resources :articles
  resources :recipes
  root to: 'home#index'
  resources :sessions, only: [:new, :create, :destroy]
  resources :user, only: [:show, :edit, :update]

  get 'user/:id/changepassword', to: 'user#change_password', as: 'change_password'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_one :recipe
  enum status: { draft: 'draft', published: 'published', deleted: 'deleted' }
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :recipe_steps, dependent: :destroy
  accepts_nested_attributes_for :recipe_steps, allow_destroy: true
  has_one_attached :photo
end

app/models/recipe_step.rb
class RecipeStep < ApplicationRecord
  belongs_to :recipe
  has_one_attached :photo
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  enum status: { registered: 'registered', active: 'active', deactivated: 'deactivated' }, _prefix: :status
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  
  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    else
      @current_user = nil
    end
  end

  def authorize
    redirect_to '/login' unless current_user
  end

  def change_user_password
    if current_user && current_user.status_registered?
      redirect_to controller: :user, action: :change_password, id: current_user.id
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < InternalController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
    @recipes = Recipe.all
  end

  # GET /articles/1/edit
  def edit
    @recipes = Recipe.all
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = set_recipe(Article.new(article_params.except(:recipe_id)))
    @article.user = current_user
    @article.status = 'draft'
    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    set_recipe(@article)    
    respond_to do |format|
      if @article.update(article_params.except(:recipe_id))
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:body, :title, :recipe_id, :abstract)
    end

    def set_recipe(article)
      recipe = Recipe.find(article_params[:recipe_id])
      article.recipe = recipe
      article
    end
end

app/controllers/home_controller.rb
class HomeController < InternalController

  def index
  end
end

app/controllers/internal_controller.rb
class InternalController < ApplicationController
  before_action :authorize, :change_user_password

end

app/controllers/recipes_controller.rb
class RecipesController < InternalController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
    20.times{@recipe.recipe_steps.build}
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:title, :ingredients, :photo, recipe_steps_attributes: [:id, :text, :photo, :order, :_destroy])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    puts "{#{params[:username]} : #{params[:password]}"
    user = User.find_by_username(params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url
    else
      flash.now[:alert] = "Invalid login"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/user_controller.rb
class UserController < InternalController
  skip_before_action :change_user_password, only: [:change_password, :update]
  before_action :set_user, only: [:show, :edit, :change_password, :update]

  def show
  end

  def edit
  end

  def change_password
  end

  def update
    if (@user.update(user_params) && @user.status_registered?)
      @user.status_active!
    end
    redirect_to @user, notice: 'Successfully updated user entry.'
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:display_name, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/application/_image_preview.html.erb
<% if image.attached? %>
  <%= image_tag(image.variant(resize: size ||= "200x200")) %>
<% else %>
  No image uploaded
<% end %>

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :recipe %>
    <% select_options = { prompt: true } %>
    <% if @article.recipe then select_options[:selected] = @recipes.index(@article.recipe) end %>
    <%= form.collection_select(:recipe_id, @recipes, :id, :title, select_options, {class: 'browser-default'}) %>
  </div>

  <div class="field">
    <%= form.label :abstract %>
    <%= form.text_area :abstract %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Articles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Recipe</th>
      <th>Abstract</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.user.display_name if article.user %></td>
        <td><%= article.recipe.title if article.recipe %></td>
        <td><%= article.abstract %></td>
        <td><%= article.status %><% if article.published? %> on <%= article.published_date %><%end%></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %> (<%= @article.status %><% if @article.published? %> : <%= @article.published_date %><% end %>)
</p>

<p>
  <strong>By:</strong>
  <%= @article.user.display_name if @article.user %>
</p>

<p>
  <strong>Recipe:</strong>
  <%= @article.recipe.title if @article.title %>
</p>

<p>
  <strong>Abstract:</strong>
  <%= @article.abstract %>
</p>

<p>
  <strong>Content:</strong>
  <%= @article.body %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FoodBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/_form.html.erb
<%= form_with(model: recipe, local: true) do |form| %>
  <% if recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :ingredients %>
    <%= form.text_field :ingredients %>
  </div>

  <div class="field">
    <%= form.label :photo %>
    <%= form.file_field :photo, accept: 'image/png, image/jpg' %>
  </div>

  <div>
    <h5>Steps:</h5>
    <% @index = 1 %>
    <%= form.fields_for :recipe_steps do |step_form| %>
      <div class="step-container">
        <hr>
	<label><%= @index%></label>
        <div>
	  <%= step_form.text_area :text %>
	  <%= step_form.hidden_field :order, :value => @index %>
	  Upload photo: <%= step_form.file_field :photo, accept: 'image/png, image/jpg'%>
	</div>
      </div>
      <% @index = @index + 1 %>
      <br />
    <% end %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Editing Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Recipes</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Ingredients</th>
      <th>Photo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recipes.each do |recipe| %>
      <tr>
        <td><%= recipe.title %></td>
        <td><%= recipe.ingredients %></td>
        <td>
          <%= render partial: 'image_preview', locals: { image: recipe.photo } %>
	</td>
        <td><%= link_to 'Show', recipe %></td>
        <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
        <td><%= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recipe', new_recipe_path %>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @recipe.title %>
</p>

<p>
  <strong>Ingredients:</strong>
  <%= @recipe.ingredients %>
</p>

<p>
  <strong>Photo:</strong>
  <%= render partial: 'image_preview', locals: {image: @recipe.photo } %>
</p>

<p>Steps</p>
<% @recipe.recipe_steps.each do |step| %>
<p><%= step.order %></p>
<div>
  <p><%= step.text %></p>
  <p>
    <%= render partial: 'image_preview', locals: {image: step.photo} %>
  </p>
<div>
<% end %>

<%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<%= link_to 'Back', recipes_path %>

app/views/user/change_password.html.erb
<p id="alert"><%= alert %></p>
<h1>Edit my account</h1>

<%= form_for @user do |form| %>
  <% if current_user.status_registered? %>
    <h3>Please change your password</h3>
  <% end %>
  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="actions">
    <%= form.submit "Update details" %>
  </div>
<% end %>

app/views/user/edit.html.erb
<p id="alert"><%= alert %></p>
<h1>Edit my account</h1>

<%= form_for @user do |form| %>
  <div class="field">
    <%= form.label :display_name %>
    <%= form.text_field :display_name %>
  </div>

  <div class="actions">
    <%= form.submit "Update details" %>
  </div>
<% end %>

app/views/user/show.html.erb
<p id="notice"><%= notice %></p>
<h1>My account details</h1>
<p>
  <strong>Display Name:</strong>
  <%= @user.display_name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Change password', change_password_path(@user) %> |
<%= link_to 'Back', root_url %>

app/views/user/update.html.erb
<h1>User#update</h1>
<p>Find me in app/views/user/update.html.erb</p>